name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  S3BUCKET: deployment-code-release-eks
  APPLICATION_NAME: book-ms

jobs:   
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - run: |
        echo "Deploying branch ${{ env.GITHUB_REF }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy push --application-name $APPLICATION_NAME --s3-location s3://${S3BUCKET}/${APPLICATION_NAME}.zip --ignore-hidden-files --region us-east-1 | sed -n 2p  | sed 's/<//g' | sed 's/>//g' | sed 's/ deployment-group-name/ book-ms/g' | sed 's/ deployment-config-name/ CodeDeployDefault.AllAtOnce/g' | sed 's/ description/ deployment/g'
